apiVersion: v1
kind: Service
metadata:
  name: grp-inicia-credito
  namespace: prd
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: grp-inicia-credito
  type: NodePort